Repository lufedev/orange-portfolio, pull requests merged in 2024-01, with the labels that each got.

#15 Criado o componente LoginInput
  my-app/package-lock.json
  my-app/package.json
  my-app/src/app/components/CustomButton.tsx
  my-app/src/app/components/LoginInput.tsx
  my-app/src/app/globals.css
  my-app/src/app/layout.tsx
  my-app/src/app/lib/definiton.ts
  my-app/src/app/page.tsx
  my-app/src/app/reset.css
  my-app/src/app/themes/Button.ts
  my-app/src/app/themes/TextField.ts
  my-app/tailwind.config.ts
Labels: documentation, enhancement

#18 Criado o componente Header
  my-app/package-lock.json
  my-app/package.json
  my-app/src/app/assets/img/avatar.png
  my-app/src/app/assets/img/logo-orangeportifolio.png
  my-app/src/app/components/CustomButton.tsx
  my-app/src/app/components/LoginInput.tsx
  my-app/src/app/components/header.tsx
  my-app/src/app/page.tsx
Labels: enhancement

#19 Criado os componentes da tela de cadastro
  my-app/src/app/components/Input.tsx
  my-app/src/app/page.tsx
  package.json
Labels: enhancement

#25 Criado o Modal SuccessModel, alterado o input password, criado um tema para o componente Header
  my-app/src/app/components/Input.tsx
  my-app/src/app/components/LoginInput.tsx
  my-app/src/app/components/SuccessModal.tsx
  my-app/src/app/components/header.tsx
  my-app/src/app/globals.css
  my-app/src/app/lib/definiton.ts
  my-app/src/app/lib/theme.ts
  my-app/src/app/page.tsx
  my-app/src/app/themes/TextField.ts
  my-app/src/app/themes/Theme.ts
Labels: bug, enhancement
